### ISSUE TITLE
Client crashes

### ISSUE THREAD

**Issue by SerVB** [SerVB/TheRecentStatOfYou#15]
With update 1.2.0.2 something became wrong.

Here is a log:

```
2018-11-30 19:55:21.100: INFO: [--- The Recent Stat of You vvv]
2018-11-30 19:55:21.100: INFO: Vehicle info task count: 0.
2018-11-30 19:55:21.100: INFO: [--- The Recent Stat of You ^^^]
2018-11-30 19:55:21.100: INFO: [--- The Recent Stat of You vvv]
2018-11-30 19:55:21.100: INFO: Tasks are joined.
2018-11-30 19:55:21.100: INFO: [--- The Recent Stat of You ^^^]
2018-11-30 19:55:21.100: INFO: [--- The Recent Stat of You vvv]
2018-11-30 19:55:21.100: INFO: Stats loaded in 0 ms. With stats: 0, with recent stats: 0, without stats: 0.
2018-11-30 19:55:21.100: INFO: [--- The Recent Stat of You ^^^]
2018-11-30 19:55:21.105: INFO: [gui.battle_control.arena_info.arena_dp] Player's team not found.
2018-11-30 19:55:21.105: INFO: [gui.battle_control.arena_info.arena_dp] Player's vehicle ID not found.
2018-11-30 19:55:21.105: INFO: [gui.battle_control.arena_info.arena_dp] Uses slow player search by name
2018-11-30 19:55:21.105: INFO: [gui.battle_control.arena_info.arena_dp] Player's team not found.
2018-11-30 19:55:21.106: INFO: [gui.battle_control.arena_info.arena_dp] Player's vehicle ID not found.
2018-11-30 19:55:21.106: INFO: [gui.battle_control.arena_info.arena_dp] Uses slow player search by name
2018-11-30 19:55:21.106: INFO: [gui.battle_control.arena_info.arena_dp] Player's team not found.
2018-11-30 19:55:21.106: INFO: [gui.battle_control.arena_info.arena_dp] Player's vehicle ID not found.
2018-11-30 19:55:21.106: INFO: [gui.battle_control.arena_info.arena_dp] Uses slow player search by name
2018-11-30 19:55:21.106: INFO: [gui.battle_control.arena_info.arena_dp] Player's team not found.
2018-11-30 19:55:21.106: INFO: [gui.battle_control.arena_info.arena_dp] Player's vehicle ID not found.
2018-11-30 19:55:21.106: INFO: [gui.battle_control.arena_info.arena_dp] Uses slow player search by name
2018-11-30 19:55:21.106: INFO: [gui.battle_control.arena_info.arena_dp] Player's team not found.
2018-11-30 19:55:21.107: INFO: [gui.battle_control.arena_info.arena_dp] Player's vehicle ID not found.
2018-11-30 19:55:21.107: INFO: [gui.battle_control.arena_info.arena_dp] Uses slow player search by name
2018-11-30 19:55:21.107: INFO: [gui.battle_control.arena_info.arena_dp] Player's team not found.
2018-11-30 19:55:21.107: INFO: [gui.battle_control.arena_info.arena_dp] Player's vehicle ID not found.
2018-11-30 19:55:21.107: INFO: [gui.battle_control.arena_info.arena_dp] Uses slow player search by name
2018-11-30 19:55:21.108: INFO: [gui.Scaleform.app_factory] Creating app: scaleform/battle
2018-11-30 19:55:22.915: ERROR: [EXCEPTION] (scripts/common/Event.py, 46):
Traceback (most recent call last):
  File "scripts/common/Event.py", line 44, in __call__
  File "scripts/client/gui/battle_control/arena_info/listeners.py", line 175, in __arena_onNewVehicleListReceived
  File "./src/scripts/client/gui/mods/mod_recent_stat_init.py", line 18, in buildVehiclesDataNew
  File "./src/scripts/client/gui/mods/mod_recent_stat_loader.py", line 50, in loadPlayerDataByVehicleList
  File "./src/scripts/client/gui/mods/mod_recent_stat_wg_stats.py", line 83, in loadPlayerDataByVehicleList
TypeError: argument of type 'NoneType' is not iterable

2018-11-30 19:55:22.915: ERROR: Traceback (most recent call last):
2018-11-30 19:55:22.915: ERROR:   File "scripts/client/Avatar.py", line 2177, in updateArena
2018-11-30 19:55:22.915: ERROR:   File "scripts/client_common/ClientArena.py", line 281, in update
2018-11-30 19:55:22.915: ERROR:   File "scripts/client_common/ClientArena.py", line 373, in __onVehicleListUpdate
2018-11-30 19:55:22.916: ERROR:   File "scripts/common/Event.py", line 44, in __call__
2018-11-30 19:55:22.916: ERROR:   File "scripts/client/gui/battle_control/arena_info/listeners.py", line 175, in __arena_onNewVehicleListReceived
2018-11-30 19:55:22.916: ERROR:   File "./src/scripts/client/gui/mods/mod_recent_stat_init.py", line 18, in buildVehiclesDataNew
2018-11-30 19:55:22.916: ERROR:   File "./src/scripts/client/gui/mods/mod_recent_stat_loader.py", line 50, in loadPlayerDataByVehicleList
2018-11-30 19:55:22.916: ERROR:   File "./src/scripts/client/gui/mods/mod_recent_stat_wg_stats.py", line 83, in loadPlayerDataByVehicleList
2018-11-30 19:55:22.916: ERROR: TypeError: argument of type 'NoneType' is not iterable
2018-11-30 19:55:23.078: NOTICE: [NOTE] (scripts/client/game.py, 477): [SPACE] Loading space: spaces/07_lakeville
2018-11-30 19:55:23.197: INFO: [gui.app_loader.loader] Space is changed: LoginSpace() -> BattleLoadingSpace()
2018-11-30 19:55:23.198: INFO: [gui.Scaleform.app_factory] Destroying app: scaleform/lobby
2018-11-30 19:55:23.210: INFO: [gui.app_loader.loader] App is destroyed: scaleform/lobby
2018-11-30 19:55:23.357: INFO: [gui.app_loader.loader] App is initializing: scaleform/battle
2018-11-30 19:55:23.576: INFO: [gui.app_loader.loader] App is initialized: scaleform/battle
2018-11-30 19:55:24.316: ERROR: Traceback (most recent call last):
2018-11-30 19:55:24.316: ERROR:   File "scripts/client/gui/Scaleform/framework/entities/BaseDAAPIComponent.py", line 76, in registerFlashComponent
2018-11-30 19:55:24.316: ERROR:   File "scripts/client/gui/Scaleform/framework/entities/DisposableEntity.py", line 63, in create
2018-11-30 19:55:24.316: ERROR:   File "scripts/client/gui/Scaleform/daapi/view/battle/shared/battle_loading.py", line 68, in _populate
2018-11-30 19:55:24.316: ERROR:   File "scripts/client/gui/battle_control/battle_session.py", line 199, in addArenaCtrl
2018-11-30 19:55:24.316: ERROR:   File "scripts/client/gui/battle_control/arena_info/listeners.py", line 776, in addController
2018-11-30 19:55:24.316: ERROR:   File "scripts/client/gui/battle_control/arena_info/listeners.py", line 165, in addController
2018-11-30 19:55:24.316: ERROR:   File "scripts/client/gui/Scaleform/daapi/view/battle/shared/battle_loading.py", line 59, in invalidateArenaInfo
2018-11-30 19:55:24.316: ERROR:   File "scripts/client/gui/Scaleform/daapi/view/battle/shared/battle_loading.py", line 94, in _setTipsInfo
2018-11-30 19:55:24.316: ERROR:   File "scripts/client/gui/battle_control/arena_info/arena_vos.py", line 572, in getTypeInfo
2018-11-30 19:55:24.316: ERROR: IndexError: tuple index out of range
2018-11-30 19:55:24.403: INFO: [gui.app_loader.loader] Space is updated: BattleLoadingSpace()
2018-11-30 19:55:24.462: INFO: [WL] Whitelist from web set to empty
2018-11-30 19:55:27.811: ERROR: [gui.battle_control.controllers.quest_progress.quest_progress_ctrl] Storage for quest:pm2_5_1_1 is not found.
2018-11-30 19:55:29.903: INFO: [gui.app_loader.loader] Space is changed: BattleLoadingSpace() -> BattleSpace()
2018-11-30 19:55:40.465: ERROR: [EXCEPTION] (scripts/common/Event.py, 46):
Traceback (most recent call last):
  File "scripts/common/Event.py", line 44, in __call__
  File "scripts/client/gui/battle_control/arena_info/listeners.py", line 229, in __arena_onAvatarReady
  File "scripts/client/gui/battle_control/arena_info/arena_dp.py", line 162, in updateVehicleStatus
KeyError: 8978250

2018-11-30 19:55:40.465: ERROR: Traceback (most recent call last):
2018-11-30 19:55:40.465: ERROR:   File "scripts/client/Avatar.py", line 2177, in updateArena
2018-11-30 19:55:40.465: ERROR:   File "scripts/client_common/ClientArena.py", line 281, in update
2018-11-30 19:55:40.465: ERROR:   File "scripts/client_common/ClientArena.py", line 458, in __onAvatarReady
2018-11-30 19:55:40.465: ERROR:   File "scripts/common/Event.py", line 44, in __call__
2018-11-30 19:55:40.465: ERROR:   File "scripts/client/gui/battle_control/arena_info/listeners.py", line 229, in __arena_onAvatarReady
2018-11-30 19:55:40.465: ERROR:   File "scripts/client/gui/battle_control/arena_info/arena_dp.py", line 162, in updateVehicleStatus
2018-11-30 19:55:40.465: ERROR: KeyError: 8978250
2018-11-30 19:55:57.766: ERROR: [EXCEPTION] (scripts/common/Event.py, 46):
Traceback (most recent call last):
  File "scripts/common/Event.py", line 44, in __call__
  File "scripts/client/gui/battle_control/arena_info/listeners.py", line 209, in __arena_onVehicleKilled
  File "scripts/client/gui/battle_control/arena_info/arena_dp.py", line 162, in updateVehicleStatus
KeyError: 8978223

2018-11-30 19:55:57.767: ERROR: Traceback (most recent call last):
2018-11-30 19:55:57.767: ERROR:   File "scripts/client/Avatar.py", line 2177, in updateArena
2018-11-30 19:55:57.767: ERROR:   File "scripts/client_common/ClientArena.py", line 281, in update
2018-11-30 19:55:57.767: ERROR:   File "scripts/client_common/ClientArena.py", line 448, in __onVehicleKilled
2018-11-30 19:55:57.767: ERROR:   File "scripts/common/Event.py", line 44, in __call__
2018-11-30 19:55:57.767: ERROR:   File "scripts/client/gui/battle_control/arena_info/listeners.py", line 209, in __arena_onVehicleKilled
2018-11-30 19:55:57.767: ERROR:   File "scripts/client/gui/battle_control/arena_info/arena_dp.py", line 162, in updateVehicleStatus
2018-11-30 19:55:57.767: ERROR: KeyError: 8978223
```

`KeyError: 8978223`: as far as I understand this player ID doesn't exist...

**Comment by n1tr0s4n** [comment]
В 1.3.0.1 без вылетов.

**Comment by n1tr0s4n** [comment]
Спасибо, ждем обнову.

**Comment by SerVB** [comment]
Сейчас вылетов не наблюдаю. Возможно, в той обнове в самих Танках был баг. Если будут вылеты, прикладывайте логи. Issue закрываю.
![shot_044](https://user-images.githubusercontent.com/20105593/50653902-26b19d80-0f9c-11e9-8e73-dbe58f57fb57.jpg)

**Comment by SerVB** [comment]
Привет. Ну без лога я ничего не смогу понять. Если еще повторится, постарайся изъять лог...

**Comment by n1tr0s4n** [comment]
ок скину

**Comment by n1tr0s4n** [comment]
sorry I'll text

**Comment by SerVB** [comment]
Только что сам поймал, вышел на первом уровне.

Видимо, нужно смотреть не на KeyError, а на это:
```
Traceback (most recent call last):
  File "scripts/common/Event.py", line 44, in __call__
  File "scripts/client/gui/battle_control/arena_info/listeners.py", line 175, in __arena_onNewVehicleListReceived
  File "./src/scripts/client/gui/mods/mod_recent_stat_init.py", line 18, in buildVehiclesDataNew
  File "./src/scripts/client/gui/mods/mod_recent_stat_loader.py", line 63, in loadPlayerDataByVehicleList
  File "./src/scripts/client/gui/mods/mod_recent_stat_wg_stats.py", line 73, in loadPlayerDataByVehicleList
TypeError: argument of type 'NoneType' is not iterable
```

Нумерация строк в компилированном файле сбита, но видимо это одна из строк <https://github.com/SerVB/TheRecentStatOfYou/blob/master/src/scripts/client/gui/mods/mod_recent_stat_wg_stats.py#L73-90>.

Посмотрю, наверно просто try-catch повешу в этом месте.

**Comment by SerVB** [comment]
Повесил в ff1e6a6951a4f683488b684d97ceccdce91be117. Поиграл на первых, не вылетело. Возможно, вылетает не в каждом бою, поэтому при продолжении проблем пишите.
